# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  download_directory: "%kernel.project_dir%/public/files"
  app.temporary_access_duration: 10
  app.mailer.from_email: 'no-reply@zenbourse.fr'
  app.mailer.from_name: 'Zenbourse'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    
  App\EventSubscriber\EasyAdminSubscriber:
    tags:
      - { name: 'kernel.event_subscriber' }

  App\Twig\Extension\AppExtension:
    tags: [twig.extension]

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
  
  # Configuration explicite pour EmailQueueService
  App\Service\EmailQueueService:
    arguments:
      $projectDir: '%kernel.project_dir%'
